version: '3'
services:
  proxy:
    build: ./proxy
    ports:
      - "80:80"
    depends_on:
      - vote
      - result

  vote:
    build: ./vote
    container_name: vote
    ports:
      - "5000:80"
    depends_on:
      - redis

  result:
    build: ./result
    container_name: result
    ports:
      - "5001:80"
    depends_on:
      - db

  worker:
    build: ./worker
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "/healthchecks/redis.sh"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "/healthchecks/postgres.sh"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db-data:
